"""Curated seed dataset: legitimate bulk/wholesale suppliers of drugs & supplements.

Categories:
  ingredient   - bulk raw ingredients for supplements/nutraceuticals
  finished     - wholesale finished supplements / OTC products
  pharma_dist  - licensed pharmaceutical wholesale distribution
  api          - active pharmaceutical ingredients / fine chemicals
  botanical    - bulk herbs & botanicals

MOQ values are typical published minimums; always confirm with the supplier.
"""

SUPPLIERS = [
    # ---------------- Bulk supplement ingredients (US/EU) ----------------
    {
        "name": "BulkSupplements.com",
        "category": "ingredient",
        "website": "https://www.bulksupplements.com",
        "country": "USA",
        "location": "Henderson, NV",
        "moq": "From 100 g; kg quantities standard",
        "certifications": ["cGMP", "FDA-registered facility", "Third-party tested"],
        "products": ["amino acids", "vitamins", "minerals", "creatine monohydrate", "caffeine anhydrous", "herbal extracts", "sweeteners"],
        "description": "Pure bulk powder ingredients sold direct-to-consumer and B2B by the gram to metric ton.",
        "tags": ["powders", "sports nutrition", "no minimum cases"],
    },
    {
        "name": "PureBulk Inc",
        "category": "ingredient",
        "website": "https://purebulk.com",
        "country": "USA",
        "location": "Roseburg, OR",
        "moq": "Gram to multi-kg sizes",
        "certifications": ["GMP", "Third-party lab tested (COA per lot)"],
        "products": ["creatine", "BCAAs", "vitamin powders", "nootropic compounds", "extracts"],
        "description": "Pure bulk nutritional powders and capsules with per-lot certificates of analysis.",
        "tags": ["powders", "COA", "sports nutrition"],
    },
    {
        "name": "NutriScience Innovations LLC",
        "category": "ingredient",
        "website": "https://www.nutriscienceusa.com",
        "country": "USA",
        "location": "Mystic, CT",
        "moq": "Kilogram scale; drum lots available",
        "certifications": ["GMP", "ISO 9001", "FDA-registered facility"],
        "products": ["NAC", "alpha-GPC", "CoQ10", "amino acids", "specialty actives"],
        "description": "Supplier of specialty nutraceutical and pharmaceutical-grade raw materials to manufacturers.",
        "tags": ["specialty chemicals", "branded ingredients"],
    },
    {
        "name": "IngredientsOnline.com",
        "category": "ingredient",
        "website": "https://www.ingredientsonline.com",
        "country": "USA",
        "location": "La Palma, CA",
        "moq": "Case/pallet via RFQ",
        "certifications": ["Vetted factory network", "GMP factories"],
        "products": ["vitamins", "minerals", "botanical extracts", "functional ingredients"],
        "description": "B2B marketplace connecting manufacturers with vetted ingredient factories; transparent pricing and COAs.",
        "tags": ["marketplace", "RFQ", "supply chain"],
    },
    {
        "name": "Prinova Global Solutions",
        "category": "ingredient",
        "website": "https://www.prinovaglobal.com",
        "country": "USA",
        "location": "Carol Stream, IL",
        "moq": "Pallet/distributor scale",
        "certifications": ["GMP warehouses", "Food safety certified"],
        "products": ["vitamins", "sweeteners", "proteins", "flavors", "custom premixes"],
        "description": "Global ingredient distributor offering blending, premixes and supply-chain services.",
        "tags": ["distributor", "premix", "blending"],
    },
    {
        "name": "Glanbia Nutritionals",
        "category": "ingredient",
        "website": "https://www.glanbianutritionals.com",
        "country": "USA",
        "location": "Chicago, IL",
        "moq": "Commercial volumes",
        "certifications": ["GMP", "FSMA compliant", "Organic options"],
        "products": ["proteins", "vitamin premixes", "functional ingredients", "grains/seeds"],
        "description": "Ingredient solutions provider: custom premix, micronization and agglomerated nutrient systems at scale.",
        "tags": ["premix", "large volume", "co-development"],
    },
    {
        "name": "Blue California",
        "category": "ingredient",
        "website": "https://www.bluecal-ingredients.com",
        "country": "USA",
        "location": "Rancho Santa Margarita, CA",
        "moq": "Kg to ton scale",
        "certifications": ["GMP", "ISO", "Fermentation-based actives"],
        "products": ["ergothioneine", "preservatives", "natural actives", "fermentation ingredients"],
        "description": "Developer and manufacturer of fermentation-derived and natural functional ingredients.",
        "tags": ["biotech", "actives", "clean label"],
    },
    {
        "name": "AIDP Inc",
        "category": "ingredient",
        "website": "https://www.aidp.com",
        "country": "USA",
        "location": "City of Industry, CA",
        "moq": "Kg to pallet",
        "certifications": ["GMP", "Branded ingredient science"],
        "products": ["Magtein magnesium L-threonate", "goFAT", "specialty nutrients"],
        "description": "Supplier of clinically researched branded nutraceutical ingredients.",
        "tags": ["branded ingredients", "clinical research"],
    },
    {
        "name": "Jiaherb Inc",
        "category": "ingredient",
        "website": "https://www.jiaherb.com",
        "country": "USA",
        "location": "Totowa, NJ",
        "moq": "Kg to drum",
        "certifications": ["GMP", "NSF-audited factories", "Organic options"],
        "products": ["botanical extracts", "fruit/vegetable powders", "standardized extracts"],
        "description": "Manufacturer-distributor of botanical extracts with in-house labs and vertically integrated farms.",
        "tags": ["botanicals", "extracts", "vertically integrated"],
    },

    # ---------------- Wholesale finished supplements ----------------
    {
        "name": "NOW Natural Foods (Wholesale)",
        "category": "finished",
        "website": "https://www.nowfoods.com",
        "country": "USA",
        "location": "Bloomingdale, IL",
        "moq": "Case quantities via distributors",
        "certifications": ["GMP", "UL-certified facilities", "Non-GMO Project", "In-house labs"],
        "products": ["vitamins", "supplements", "sports nutrition", "personal care", "essential oils"],
        "description": "Family-owned natural products manufacturer selling wholesale through authorized distributors.",
        "tags": ["brand owner", "authorized distributors"],
    },
    {
        "name": "Piping Rock Health Products",
        "category": "finished",
        "website": "https://www.pipingrock.com",
        "country": "USA",
        "location": "Ronkonkoma, NY",
        "moq": "Low case minimums; private label available",
        "certifications": ["GMP", "In-house quality control"],
        "products": ["supplements", "essential oils", "vitamins", "herbal products"],
        "description": "Vertically integrated manufacturer offering finished supplements plus private-label programs.",
        "tags": ["private label", "own manufacturing"],
    },
    {
        "name": "Hard Rhino / BulkSupplements Private Label",
        "category": "finished",
        "website": "https://www.hardrhino.com",
        "country": "USA",
        "location": "Henderson, NV",
        "moq": "Small case minimums",
        "certifications": ["cGMP", "Lot-tested"],
        "products": ["capsules", "bulk powders", "private label supplements"],
        "description": "Finished-goods arm for private label sports nutrition and supplement products.",
        "tags": ["private label", "capsules"],
    },

    # ---------------- Botanical / herb wholesalers ----------------
    {
        "name": "Starwest Botanicals",
        "category": "botanical",
        "website": "https://www.starwest-botanicals.com",
        "country": "USA",
        "location": "Sacramento, CA",
        "moq": "Ounce to bulk sack",
        "certifications": ["USDA Organic", "cGMP", "Kosher"],
        "products": ["dried herbs", "spices", "essential oils", "teas", "powdered botanicals"],
        "description": "One of the largest bulk herb suppliers in the US; organic-certified processing facility.",
        "tags": ["organic herbs", "spices", "tea"],
    },
    {
        "name": "Mountain Rose Herbs",
        "category": "botanical",
        "website": "https://www.mountainroseherbs.com",
        "country": "USA",
        "location": "Eugene, OR",
        "moq": "No true minimum; bulk discounts",
        "certifications": ["USDA Organic", "Fair Trade partner", "Zero-waste facility"],
        "products": ["bulk herbs", "extracts", "essential oils", "clays", "carrier oils"],
        "description": "Certified organic processor of botanical goods emphasizing sustainability.",
        "tags": ["organic", "sustainable", "aromatherapy"],
    },
    {
        "name": "Monterey Bay Spice Co.",
        "category": "botanical",
        "website": "https://www.herbco.com",
        "country": "USA",
        "location": "Watsonville, CA",
        "moq": "Quarter-pound up",
        "certifications": ["Organic options", "Quality-tested botanicals"],
        "products": ["culinary herbs", "spices", "tea blends", "capsules"],
        "description": "Bulk herbs and spices for food, cosmetic and supplement makers.",
        "tags": ["culinary", "small business friendly"],
    },
    {
        "name": "Atlantic Spice Company",
        "category": "botanical",
        "website": "https://www.atlanticspice.com",
        "country": "USA",
        "location": "North Truro, MA",
        "moq": "Pound quantities",
        "certifications": ["Food-grade handling"],
        "products": ["spices", "herbs", "baking ingredients", "sea vegetables"],
        "description": "Wholesale spice and herb house serving small manufacturers since 1990.",
        "tags": ["spices", "food service"],
    },
    {
        "name": "San Francisco Herb & Natural Food Co.",
        "category": "botanical",
        "website": "https://www.sfherb.com",
        "country": "USA",
        "location": "San Leandro, CA",
        "moq": "Pound quantities",
        "certifications": ["Organic lines available"],
        "products": ["bulk herbs", "spices", "potpourri botanicals"],
        "description": "Long-running West Coast wholesaler of herbs, spices and botanicals.",
        "tags": ["herbs", "crafters"],
    },

    # ---------------- Research / fine chemicals & APIs ----------------
    {
        "name": "Cayman Chemical",
        "category": "api",
        "website": "https://www.caymanchem.com",
        "country": "USA",
        "location": "Ann Arbor, MI",
        "moq": "mg to kg (research to pilot)",
        "certifications": ["GMP contract manufacturing", "ISO 13485 devices line"],
        "products": ["reference standards", "bioactive small molecules", "assay kits"],
        "description": "Chemical supplier and GMP contract manufacturer for pharmaceutical R&D.",
        "tags": ["research chemicals", "standards", "GMP scale-up"],
    },
    {
        "name": "Sigma-Aldrich (Merck KGaA)",
        "category": "api",
        "website": "https://www.sigmaaldrich.com",
        "country": "Germany/USA",
        "location": "Darmstadt, DE / St. Louis, MO",
        "moq": "Gram to ton",
        "certifications": ["ISO 9001", "Pharmacopeia grade (USP/EP)", "GMP sites"],
        "products": ["pharmaceutical excipients", "analytical standards", "fine chemicals", "buffers"],
        "description": "Global life-science catalog supplier covering lab through production volumes.",
        "tags": ["catalog giant", "excipients", "global"],
    },
    {
        "name": "Alfa Chemistry",
        "category": "api",
        "website": "https://www.alfa.com",
        "country": "USA",
        "location": "Stony Brook, NY",
        "moq": "Gram to kg",
        "certifications": ["Analytical COAs provided"],
        "products": ["organic reagents", "pharmaceutical impurity standards", "intermediates"],
        "description": "Catalog supplier of organic and analytical chemistry reagents worldwide.",
        "tags": ["reagents", "impurities", "intermediates"],
    },
    {
        "name": "Suanfarma",
        "category": "api",
        "website": "https://www.suanfarma.com",
        "country": "Spain/USA",
        "location": "Madrid, ES / Rocky Hill, NJ",
        "moq": "Commercial API volumes",
        "certifications": ["EU GMP", "US FDA-inspected plants", "CEP/DMF filings"],
        "products": ["APIs", "HPAPIs", "intermediates", "CDMO services"],
        "description": "API manufacturer and CDMO with FDA/EMA-inspected facilities on both continents.",
        "tags": ["CDMO", "DMF", "regulated markets"],
    },
    {
        "name": "PharmaCompass",
        "category": "api",
        "website": "https://www.pharmacompass.com",
        "country": "India",
        "location": "Hyderabad, IN",
        "moq": "Quote-based",
        "certifications": ["Directory of DMF/CEP holders"],
        "products": ["API sourcing", "supplier discovery", "regulatory intelligence"],
        "description": "Sourcing platform listing verified API manufacturers with DMF/CEP documentation status.",
        "tags": ["marketplace", "sourcing", "directory"],
    },
    {
        "name": "Xi'an Natural Field Biotechnology",
        "category": "api",
        "website": "https://www.naturalfield.com",
        "country": "China",
        "location": "Xi'an, CN",
        "moq": "Kg scale; samples available",
        "certifications": ["ISO 9001", "Halal/Kosher lines", "Export COA per batch"],
        "products": ["plant extracts", "nutraceutical raws", "cosmetic actives"],
        "description": "Chinese extract manufacturer exporting standardized botanical and synthetic ingredients.",
        "tags": ["exporter", "extracts"],
    },
    {
        "name": "Hunan Nutramax Inc.",
        "category": "api",
        "website": "https://www.nutramax.com.cn",
        "country": "China",
        "location": "Changsha, CN",
        "moq": "Kg to drum",
        "certifications": ["ISO 9001", "GMP workshops", "Kosher/Halal"],
        "products": ["botanical extracts", "monomer actives", "fruit powders"],
        "description": "High-volume botanical extraction plant supplying global supplement brands.",
        "tags": ["extracts", "high volume"],
    },

    # ---------------- Licensed pharmaceutical distribution ----------------
    {
        "name": "McKesson Corporation",
        "category": "pharma_dist",
        "website": "https://www.mckesson.com",
        "country": "USA",
        "location": "Irving, TX",
        "moq": "Account-based; daily order cycles",
        "certifications": ["State pharmacy licenses", "DEA registration", "VAWD-accredited DCs"],
        "products": ["full-line Rx distribution", "OTC", "generics", "pharmacy supplies"],
        "description": "Largest US pharmaceutical distributor serving pharmacies, health systems and providers.",
        "tags": ["big three distributor", "licensed wholesale"],
    },
    {
        "name": "Cencora (formerly AmerisourceBergen)",
        "category": "pharma_dist",
        "website": "https://www.cencora.com",
        "country": "USA",
        "location": "Conshohocken, PA",
        "moq": "Account-based",
        "certifications": ["DEA registration", "State licensing", "PDURS compliance"],
        "products": ["full-line Rx distribution", "specialty drugs", "vaccines", "generics"],
        "description": "Global pharmaceutical sourcing and distribution services company.",
        "tags": ["big three distributor", "specialty"],
    },
    {
        "name": "Cardinal Health (Pharmaceutical Segment)",
        "category": "pharma_dist",
        "website": "https://www.cardinalhealth.com",
        "country": "USA",
        "location": "Dublin, OH",
        "moq": "Account-based",
        "certifications": ["DEA registration", "Licensed wholesale", "Accredited DC network"],
        "products": ["Rx distribution", "OTC", "nuclear pharmacy services"],
        "description": "Distributor and manufacturer of medical/pharmaceutical products to care sites.",
        "tags": ["big three distributor"],
    },
    {
        "name": "Morris & Dickson Co., LLC",
        "category": "pharma_dist",
        "website": "https://www.morrisdickson.com",
        "country": "USA",
        "location": "Shreveport, LA",
        "moq": "Independent-pharmacy friendly",
        "certifications": ["DEA registration", "State licenses", "VAWD accreditation"],
        "products": ["full-line Rx", "OTC", "veterinary lines"],
        "description": "Family-owned full-line pharmaceutical wholesaler serving independent pharmacies since 1841.",
        "tags": ["independent pharmacies", "family owned"],
    },
    {
        "name": "Smith Drug Company",
        "category": "pharma_dist",
        "website": "https://www.smithdrug.com",
        "country": "USA",
        "location": "Spartanburg, SC",
        "moq": "Regional account terms",
        "certifications": ["DEA registration", "State wholesale licenses"],
        "products": ["Rx distribution", "OTC", "front-end store supplies"],
        "description": "Southeastern regional drug wholesaler for independent community pharmacies.",
        "tags": ["regional wholesaler"],
    },
]


def validate(rows):
    seen = set()
    for r in rows:
        assert r["name"] not in seen, f"Duplicate: {r['name']}"
        seen.add(r["name"])
        assert r["category"] in {"ingredient", "finished", "pharma_dist", "api", "botanical"}, r["name"]
    return rows


if __name__ == "__main__":
    print(f"{len(validate(SUPPLIERS))} suppliers validated")
