"""Curated seed dataset: legitimate bulk/wholesale suppliers of drugs & supplements.

Categories:
  ingredient   - bulk raw ingredients for supplements/nutraceuticals
  finished     - wholesale finished supplements / OTC products
  pharma_dist  - licensed pharmaceutical wholesale distribution
  api          - active pharmaceutical ingredients / fine chemicals
  botanical    - bulk herbs & botanicals

MOQ values are typical published minimums; always confirm with the supplier.
"""

SUPPLIERS = [
    # ---------------- Bulk supplement ingredients (US/EU) ----------------
    {
        "name": "BulkSupplements.com",
        "category": "ingredient",
        "website": "https://www.bulksupplements.com",
        "country": "USA",
        "location": "Henderson, NV",
        "moq": "From 100 g; kg quantities standard",
        "certifications": ["cGMP", "FDA-registered facility", "Third-party tested"],
        "products": ["amino acids", "vitamins", "minerals", "creatine monohydrate", "caffeine anhydrous", "herbal extracts", "sweeteners"],
        "description": "Pure bulk powder ingredients sold direct-to-consumer and B2B by the gram to metric ton.",
        "tags": ["powders", "sports nutrition", "no minimum cases"],
    },
    {
        "name": "PureBulk Inc",
        "category": "ingredient",
        "website": "https://purebulk.com",
        "country": "USA",
        "location": "Roseburg, OR",
        "moq": "Gram to multi-kg sizes",
        "certifications": ["GMP", "Third-party lab tested (COA per lot)"],
        "products": ["creatine", "BCAAs", "vitamin powders", "nootropic compounds", "extracts"],
        "description": "Pure bulk nutritional powders and capsules with per-lot certificates of analysis.",
        "tags": ["powders", "COA", "sports nutrition"],
    },
    {
        "name": "NutriScience Innovations LLC",
        "category": "ingredient",
        "website": "https://www.nutriscienceusa.com",
        "country": "USA",
        "location": "Mystic, CT",
        "moq": "Kilogram scale; drum lots available",
        "certifications": ["GMP", "ISO 9001", "FDA-registered facility"],
        "products": ["NAC", "alpha-GPC", "CoQ10", "amino acids", "specialty actives"],
        "description": "Supplier of specialty nutraceutical and pharmaceutical-grade raw materials to manufacturers.",
        "tags": ["specialty chemicals", "branded ingredients"],
    },
    {
        "name": "IngredientsOnline.com",
        "category": "ingredient",
        "website": "https://www.ingredientsonline.com",
        "country": "USA",
        "location": "La Palma, CA",
        "moq": "Case/pallet via RFQ",
        "certifications": ["Vetted factory network", "GMP factories"],
        "products": ["vitamins", "minerals", "botanical extracts", "functional ingredients"],
        "description": "B2B marketplace connecting manufacturers with vetted ingredient factories; transparent pricing and COAs.",
        "tags": ["marketplace", "RFQ", "supply chain"],
    },
    {
        "name": "Prinova Global Solutions",
        "category": "ingredient",
        "website": "https://www.prinovaglobal.com",
        "country": "USA",
        "location": "Carol Stream, IL",
        "moq": "Pallet/distributor scale",
        "certifications": ["GMP warehouses", "Food safety certified"],
        "products": ["vitamins", "sweeteners", "proteins", "flavors", "custom premixes"],
        "description": "Global ingredient distributor offering blending, premixes and supply-chain services.",
        "tags": ["distributor", "premix", "blending"],
    },
    {
        "name": "Glanbia Nutritionals",
        "category": "ingredient",
        "website": "https://www.glanbianutritionals.com",
        "country": "USA",
        "location": "Chicago, IL",
        "moq": "Commercial volumes",
        "certifications": ["GMP", "FSMA compliant", "Organic options"],
        "products": ["proteins", "vitamin premixes", "functional ingredients", "grains/seeds"],
        "description": "Ingredient solutions provider: custom premix, micronization and agglomerated nutrient systems at scale.",
        "tags": ["premix", "large volume", "co-development"],
    },
    {
        "name": "Blue California",
        "category": "ingredient",
        "website": "https://www.bluecal-ingredients.com",
        "country": "USA",
        "location": "Rancho Santa Margarita, CA",
        "moq": "Kg to ton scale",
        "certifications": ["GMP", "ISO", "Fermentation-based actives"],
        "products": ["ergothioneine", "preservatives", "natural actives", "fermentation ingredients"],
        "description": "Developer and manufacturer of fermentation-derived and natural functional ingredients.",
        "tags": ["biotech", "actives", "clean label"],
    },
    {
        "name": "AIDP Inc",
        "category": "ingredient",
        "website": "https://www.aidp.com",
        "country": "USA",
        "location": "City of Industry, CA",
        "moq": "Kg to pallet",
        "certifications": ["GMP", "Branded ingredient science"],
        "products": ["Magtein magnesium L-threonate", "goFAT", "specialty nutrients"],
        "description": "Supplier of clinically researched branded nutraceutical ingredients.",
        "tags": ["branded ingredients", "clinical research"],
    },
    {
        "name": "Jiaherb Inc",
        "category": "ingredient",
        "website": "https://www.jiaherb.com",
        "country": "USA",
        "location": "Totowa, NJ",
        "moq": "Kg to drum",
        "certifications": ["GMP", "NSF-audited factories", "Organic options"],
        "products": ["botanical extracts", "fruit/vegetable powders", "standardized extracts"],
        "description": "Manufacturer-distributor of botanical extracts with in-house labs and vertically integrated farms.",
        "tags": ["botanicals", "extracts", "vertically integrated"],
    },

    # ---------------- Wholesale finished supplements ----------------
    {
        "name": "NOW Natural Foods (Wholesale)",
        "category": "finished",
        "website": "https://www.nowfoods.com",
        "country": "USA",
        "location": "Bloomingdale, IL",
        "moq": "Case quantities via distributors",
        "certifications": ["GMP", "UL-certified facilities", "Non-GMO Project", "In-house labs"],
        "products": ["vitamins", "supplements", "sports nutrition", "personal care", "essential oils"],
        "description": "Family-owned natural products manufacturer selling wholesale through authorized distributors.",
        "tags": ["brand owner", "authorized distributors"],
    },
    {
        "name": "Piping Rock Health Products",
        "category": "finished",
        "website": "https://www.pipingrock.com",
        "country": "USA",
        "location": "Ronkonkoma, NY",
        "moq": "Low case minimums; private label available",
        "certifications": ["GMP", "In-house quality control"],
        "products": ["supplements", "essential oils", "vitamins", "herbal products"],
        "description": "Vertically integrated manufacturer offering finished supplements plus private-label programs.",
        "tags": ["private label", "own manufacturing"],
    },
    {
        "name": "Hard Rhino / BulkSupplements Private Label",
        "category": "finished",
        "website": "https://www.hardrhino.com",
        "country": "USA",
        "location": "Henderson, NV",
        "moq": "Small case minimums",
        "certifications": ["cGMP", "Lot-tested"],
        "products": ["capsules", "bulk powders", "private label supplements"],
        "description": "Finished-goods arm for private label sports nutrition and supplement products.",
        "tags": ["private label", "capsules"],
    },

    # ---------------- Botanical / herb wholesalers ----------------
    {
        "name": "Starwest Botanicals",
        "category": "botanical",
        "website": "https://www.starwest-botanicals.com",
        "country": "USA",
        "location": "Sacramento, CA",
        "moq": "Ounce to bulk sack",
        "certifications": ["USDA Organic", "cGMP", "Kosher"],
        "products": ["dried herbs", "spices", "essential oils", "teas", "powdered botanicals"],
        "description": "One of the largest bulk herb suppliers in the US; organic-certified processing facility.",
        "tags": ["organic herbs", "spices", "tea"],
    },
    {
        "name": "Mountain Rose Herbs",
        "category": "botanical",
        "website": "https://www.mountainroseherbs.com",
        "country": "USA",
        "location": "Eugene, OR",
        "moq": "No true minimum; bulk discounts",
        "certifications": ["USDA Organic", "Fair Trade partner", "Zero-waste facility"],
        "products": ["bulk herbs", "extracts", "essential oils", "clays", "carrier oils"],
        "description": "Certified organic processor of botanical goods emphasizing sustainability.",
        "tags": ["organic", "sustainable", "aromatherapy"],
    },
    {
        "name": "Monterey Bay Spice Co.",
        "category": "botanical",
        "website": "https://www.herbco.com",
        "country": "USA",
        "location": "Watsonville, CA",
        "moq": "Quarter-pound up",
        "certifications": ["Organic options", "Quality-tested botanicals"],
        "products": ["culinary herbs", "spices", "tea blends", "capsules"],
        "description": "Bulk herbs and spices for food, cosmetic and supplement makers.",
        "tags": ["culinary", "small business friendly"],
    },
    {
        "name": "Atlantic Spice Company",
        "category": "botanical",
        "website": "https://www.atlanticspice.com",
        "country": "USA",
        "location": "North Truro, MA",
        "moq": "Pound quantities",
        "certifications": ["Food-grade handling"],
        "products": ["spices", "herbs", "baking ingredients", "sea vegetables"],
        "description": "Wholesale spice and herb house serving small manufacturers since 1990.",
        "tags": ["spices", "food service"],
    },
    {
        "name": "San Francisco Herb & Natural Food Co.",
        "category": "botanical",
        "website": "https://www.sfherb.com",
        "country": "USA",
        "location": "San Leandro, CA",
        "moq": "Pound quantities",
        "certifications": ["Organic lines available"],
        "products": ["bulk herbs", "spices", "potpourri botanicals"],
        "description": "Long-running West Coast wholesaler of herbs, spices and botanicals.",
        "tags": ["herbs", "crafters"],
    },

    # ---------------- Research / fine chemicals & APIs ----------------
    {
        "name": "Cayman Chemical",
        "category": "api",
        "website": "https://www.caymanchem.com",
        "country": "USA",
        "location": "Ann Arbor, MI",
        "moq": "mg to kg (research to pilot)",
        "certifications": ["GMP contract manufacturing", "ISO 13485 devices line"],
        "products": ["reference standards", "bioactive small molecules", "assay kits"],
        "description": "Chemical supplier and GMP contract manufacturer for pharmaceutical R&D.",
        "tags": ["research chemicals", "standards", "GMP scale-up"],
    },
    {
        "name": "Sigma-Aldrich (Merck KGaA)",
        "category": "api",
        "website": "https://www.sigmaaldrich.com",
        "country": "Germany/USA",
        "location": "Darmstadt, DE / St. Louis, MO",
        "moq": "Gram to ton",
        "certifications": ["ISO 9001", "Pharmacopeia grade (USP/EP)", "GMP sites"],
        "products": ["pharmaceutical excipients", "analytical standards", "fine chemicals", "buffers"],
        "description": "Global life-science catalog supplier covering lab through production volumes.",
        "tags": ["catalog giant", "excipients", "global"],
    },
    {
        "name": "Alfa Chemistry",
        "category": "api",
        "website": "https://www.alfa.com",
        "country": "USA",
        "location": "Stony Brook, NY",
        "moq": "Gram to kg",
        "certifications": ["Analytical COAs provided"],
        "products": ["organic reagents", "pharmaceutical impurity standards", "intermediates"],
        "description": "Catalog supplier of organic and analytical chemistry reagents worldwide.",
        "tags": ["reagents", "impurities", "intermediates"],
    },
    {
        "name": "Suanfarma",
        "category": "api",
        "website": "https://www.suanfarma.com",
        "country": "Spain/USA",
        "location": "Madrid, ES / Rocky Hill, NJ",
        "moq": "Commercial API volumes",
        "certifications": ["EU GMP", "US FDA-inspected plants", "CEP/DMF filings"],
        "products": ["APIs", "HPAPIs", "intermediates", "CDMO services"],
        "description": "API manufacturer and CDMO with FDA/EMA-inspected facilities on both continents.",
        "tags": ["CDMO", "DMF", "regulated markets"],
    },
    {
        "name": "PharmaCompass",
        "category": "api",
        "website": "https://www.pharmacompass.com",
        "country": "India",
        "location": "Hyderabad, IN",
        "moq": "Quote-based",
        "certifications": ["Directory of DMF/CEP holders"],
        "products": ["API sourcing", "supplier discovery", "regulatory intelligence"],
        "description": "Sourcing platform listing verified API manufacturers with DMF/CEP documentation status.",
        "tags": ["marketplace", "sourcing", "directory"],
    },
    {
        "name": "Xi'an Natural Field Biotechnology",
        "category": "api",
        "website": "https://www.naturalfield.com",
        "country": "China",
        "location": "Xi'an, CN",
        "moq": "Kg scale; samples available",
        "certifications": ["ISO 9001", "Halal/Kosher lines", "Export COA per batch"],
        "products": ["plant extracts", "nutraceutical raws", "cosmetic actives"],
        "description": "Chinese extract manufacturer exporting standardized botanical and synthetic ingredients.",
        "tags": ["exporter", "extracts"],
    },
    {
        "name": "Hunan Nutramax Inc.",
        "category": "api",
        "website": "https://www.nutramax.com.cn",
        "country": "China",
        "location": "Changsha, CN",
        "moq": "Kg to drum",
        "certifications": ["ISO 9001", "GMP workshops", "Kosher/Halal"],
        "products": ["botanical extracts", "monomer actives", "fruit powders"],
        "description": "High-volume botanical extraction plant supplying global supplement brands.",
        "tags": ["extracts", "high volume"],
    },

    # ---------------- Licensed pharmaceutical distribution ----------------
    {
        "name": "McKesson Corporation",
        "category": "pharma_dist",
        "website": "https://www.mckesson.com",
        "country": "USA",
        "location": "Irving, TX",
        "moq": "Account-based; daily order cycles",
        "certifications": ["State pharmacy licenses", "DEA registration", "VAWD-accredited DCs"],
        "products": ["full-line Rx distribution", "OTC", "generics", "pharmacy supplies"],
        "description": "Largest US pharmaceutical distributor serving pharmacies, health systems and providers.",
        "tags": ["big three distributor", "licensed wholesale"],
    },
    {
        "name": "Cencora (formerly AmerisourceBergen)",
        "category": "pharma_dist",
        "website": "https://www.cencora.com",
        "country": "USA",
        "location": "Conshohocken, PA",
        "moq": "Account-based",
        "certifications": ["DEA registration", "State licensing", "PDURS compliance"],
        "products": ["full-line Rx distribution", "specialty drugs", "vaccines", "generics"],
        "description": "Global pharmaceutical sourcing and distribution services company.",
        "tags": ["big three distributor", "specialty"],
    },
    {
        "name": "Cardinal Health (Pharmaceutical Segment)",
        "category": "pharma_dist",
        "website": "https://www.cardinalhealth.com",
        "country": "USA",
        "location": "Dublin, OH",
        "moq": "Account-based",
        "certifications": ["DEA registration", "Licensed wholesale", "Accredited DC network"],
        "products": ["Rx distribution", "OTC", "nuclear pharmacy services"],
        "description": "Distributor and manufacturer of medical/pharmaceutical products to care sites.",
        "tags": ["big three distributor"],
    },
    {
        "name": "Morris & Dickson Co., LLC",
        "category": "pharma_dist",
        "website": "https://www.morrisdickson.com",
        "country": "USA",
        "location": "Shreveport, LA",
        "moq": "Independent-pharmacy friendly",
        "certifications": ["DEA registration", "State licenses", "VAWD accreditation"],
        "products": ["full-line Rx", "OTC", "veterinary lines"],
        "description": "Family-owned full-line pharmaceutical wholesaler serving independent pharmacies since 1841.",
        "tags": ["independent pharmacies", "family owned"],
    },
    {
        "name": "Smith Drug Company",
        "category": "pharma_dist",
        "website": "https://www.smithdrug.com",
        "country": "USA",
        "location": "Spartanburg, SC",
        "moq": "Regional account terms",
        "certifications": ["DEA registration", "State wholesale licenses"],
        "products": ["Rx distribution", "OTC", "front-end store supplies"],
        "description": "Southeastern regional drug wholesaler for independent community pharmacies.",
        "tags": ["regional wholesaler"],
    },
]


def validate(rows):
    seen = set()
    for r in rows:
        assert r["name"] not in seen, f"Duplicate: {r['name']}"
        seen.add(r["name"])
        assert r["category"] in {
            "ingredient", "finished", "pharma_dist", "api", "botanical", "marketplace"
        }, r["name"]
    return rows


# ---------------------------------------------------------------------------
# Pricing & pack-size enrichment.
# Prices are INDICATIVE list/range figures for typical bulk quantities, meant
# for comparison shopping only; confirm current quotes with the supplier.
# ---------------------------------------------------------------------------
PRICE_AND_PACKS: dict[str, dict] = {
    "BulkSupplements.com": {
        "pack_sizes": ["100 g", "500 g", "1 kg", "5 kg", "25 kg"],
        "pricing_note": "Per-kg price drops sharply at 5 kg+ tiers",
        "price_examples": [
            {"item": "Creatine monohydrate", "price": "$16–26", "unit": "kg"},
            {"item": "Caffeine anhydrous", "price": "$12–20", "unit": "kg"},
            {"item": "L-Glutamine", "price": "$14–22", "unit": "kg"},
        ],
    },
    "PureBulk Inc": {
        "pack_sizes": ["100 g", "250 g", "1 kg", "5 kg", "20 kg"],
        "pricing_note": "COA per lot included in price",
        "price_examples": [
            {"item": "Creatine monohydrate (Creapure)", "price": "$45–65", "unit": "kg"},
            {"item": "Creatine monohydrate (generic)", "price": "$18–30", "unit": "kg"},
            {"item": "Beta-alanine", "price": "$20–32", "unit": "kg"},
        ],
    },
    "NutriScience Innovations LLC": {
        "pack_sizes": ["1 kg", "5 kg", "25 kg drum"],
        "pricing_note": "Quote-based above 25 kg",
        "price_examples": [
            {"item": "NAC", "price": "$28–45", "unit": "kg"},
            {"item": "Alpha-GPC 50% powder", "price": "$60–95", "unit": "kg"},
        ],
    },
    "IngredientsOnline.com": {
        "pack_sizes": ["25 kg carton", "50 lb fiber drum", "pallet"],
        "pricing_note": "Transparent tiered list pricing on site; RFQ for pallets",
        "price_examples": [
            {"item": "Vitamin C ascorbic acid", "price": "$8–15", "unit": "kg"},
            {"item": "Magnesium glycinate", "price": "$14–24", "unit": "kg"},
        ],
    },
    "Prinova Global Solutions": {
        "pack_sizes": ["bag", "box", "pallet", "bulk truckload"],
        "pricing_note": "Contract/distributor pricing via account reps",
        "price_examples": [
            {"item": "Sweeteners & proteins", "price": "Quote", "unit": "per lot"},
        ],
    },
    "Glanbia Nutritionals": {
        "pack_sizes": ["custom premix batches", "tote/pallet"],
        "pricing_note": "Custom-quoted premix programs",
        "price_examples": [
            {"item": "Vitamin premix blends", "price": "Quote", "unit": "per batch"},
        ],
    },
    "Blue California": {
        "pack_sizes": ["1 kg", "5 kg", "25 kg"],
        "pricing_note": "Premium fermentation-derived actives",
        "price_examples": [
            {"item": "L-Ergothioneine", "price": "$800–1500", "unit": "kg"},
        ],
    },
    "AIDP Inc": {
        "pack_sizes": ["1 kg", "5 kg", "25 kg drum"],
        "pricing_note": "Branded ingredients carry premium vs commodity",
        "price_examples": [
            {"item": "Magtein (Mg L-threonate)", "price": "$90–140", "unit": "kg"},
        ],
    },
    "Jiaherb Inc": {
        "pack_sizes": ["1 kg", "5 kg", "25 kg drum"],
        "pricing_note": "Standardization ratio drives price",
        "price_examples": [
            {"item": "Curcuminoids 95% extract", "price": "$30–55", "unit": "kg"},
            {"item": "Green tea extract 50% EGCG", "price": "$25–45", "unit": "kg"},
        ],
    },
    "NOW Natural Foods (Wholesale)": {
        "pack_sizes": ["case of 6–12 units", "master case"],
        "pricing_note": "Wholesale ~40-50% off MSRP via distributors",
        "price_examples": [
            {"item": "Finished bottles (typ. 60–120 ct)", "price": "$6–25", "unit": "bottle wholesale"},
        ],
    },
    "Piping Rock Health Products": {
        "pack_sizes": ["case packs", "private label runs from ~1k units"],
        "pricing_note": "Private label quoted per SKU and run length",
        "price_examples": [
            {"item": "Stock supplements wholesale", "price": "$2–12", "unit": "bottle"},
        ],
    },
    "Hard Rhino / BulkSupplements Private Label": {
        "pack_sizes": ["cases", "pallets"],
        "pricing_note": "Low case minimums; label setup fee may apply",
        "price_examples": [
            {"item": "Capsules (stock formulas)", "price": "$3–10", "unit": "bottle"},
        ],
    },
    "Starwest Botanicals": {
        "pack_sizes": ["4 oz", "1 lb", "5 lb", "25 lb sack"],
        "pricing_note": "Organic line priced above conventional",
        "price_examples": [
            {"item": "Organic chamomile flowers whole", "price": "$12–22", "unit": "lb"},
            {"item": "Organic turmeric powder", "price": "$6–12", "unit": "lb"},
        ],
    },
    "Mountain Rose Herbs": {
        "pack_sizes": ["4 oz", "1 lb", "5 lb", "25 lb"],
        "pricing_note": "No minimum order; bulk pricing tiers online",
        "price_examples": [
            {"item": "Organic nettle leaf c/s", "price": "$9–16", "unit": "lb"},
            {"item": "Organic lavender flowers", "price": "$14–26", "unit": "lb"},
        ],
    },
    "Monterey Bay Spice Co.": {
        "pack_sizes": ["1/4 lb", "1 lb", "5 lb", "25 lb"],
        "pricing_note": "Small-business friendly pack ladder",
        "price_examples": [
            {"item": "Hibiscus flowers c/s", "price": "$5–10", "unit": "lb"},
        ],
    },
    "Atlantic Spice Company": {
        "pack_sizes": ["1 lb", "5 lb", "25 lb box"],
        "pricing_note": "Volume breaks at 5/25 lb",
        "price_examples": [
            {"item": "Cinnamon powder (cassia)", "price": "$3–7", "unit": "lb"},
        ],
    },
    "San Francisco Herb & Natural Food Co.": {
        "pack_sizes": ["1 lb", "5 lb", "25 lb"],
        "pricing_note": "Long-standing flat wholesale tiers",
        "price_examples": [
            {"item": "Rosemary leaf whole", "price": "$4–9", "unit": "lb"},
        ],
    },
    "Cayman Chemical": {
        "pack_sizes": ["mg vials", "g lots", "multi-kg GMP campaigns"],
        "pricing_note": "Research mg-g; GMP scale-up separately quoted",
        "price_examples": [
            {"item": "Bioactive reference standards", "price": "$50–400", "unit": "vial"},
        ],
    },
    "Sigma-Aldrich (Merck KGaA)": {
        "pack_sizes": ["g bottles", "kg pails", "ton IBC"],
        "pricing_note": "Catalog list prices; volume contracts via sales",
        "price_examples": [
            {"item": "USP-grade excipients", "price": "$40–200+", "unit": "kg catalog"},
        ],
    },
    "Alfa Chemistry": {
        "pack_sizes": ["g", "100 g", "kg"],
        "pricing_note": "Impurity standards often $100+/10 mg",
        "price_examples": [
            {"item": "Pharmaceutical impurity standards", "price": "$100–600", "unit": "10 mg–1 g"},
        ],
    },
    "Suanfarma": {
        "pack_sizes": ["kg commercial packs", "drum (25–50 kg)", "container"],
        "pricing_note": "Contract API pricing with DMF support",
        "price_examples": [
            {"item": "Commercial APIs", "price": "Quote / contract", "unit": "kg"},
        ],
    },
    "PharmaCompass": {
        "pack_sizes": ["n/a (RFQ platform)"],
        "pricing_note": "Free RFQ to multiple DMF-holding factories",
        "price_examples": [
            {"item": "API quotes", "price": "Quote", "unit": "per RFQ"},
        ],
    },
    "Xi'an Natural Field Biotechnology": {
        "pack_sizes": ["1 kg foil bag", "25 kg drum"],
        "pricing_note": "FOB China; samples free with freight collect",
        "price_examples": [
            {"item": "Plant extracts (standardized)", "price": "$10–80", "unit": "kg FOB"},
        ],
    },
    "Hunan Nutramax Inc.": {
        "pack_sizes": ["1 kg", "25 kg drum"],
        "pricing_note": "High-volume export pricing",
        "price_examples": [
            {"item": "Botanical extracts", "price": "$8–60", "unit": "kg FOB"},
        ],
    },
    "McKesson Corporation": {
        "pack_sizes": ["each", "case"],
        "pricing_note": "WAC + contract pricing; requires pharmacy license/account",
        "price_examples": [
            {"item": "Brand & generic Rx", "price": "WAC/contract", "unit": "per account"},
        ],
    },
    "Cencora (formerly AmerisourceBergen)": {
        "pack_sizes": ["each", "case"],
        "pricing_note": "WAC/contract; specialty buy-side programs",
        "price_examples": [
            {"item": "Rx distribution", "price": "WAC/contract", "unit": "per account"},
        ],
    },
    "Cardinal Health (Pharmaceutical Segment)": {
        "pack_sizes": ["each", "case"],
        "pricing_note": "WAC/contract; generics programs available",
        "price_examples": [
            {"item": "Rx distribution", "price": "WAC/contract", "unit": "per account"},
        ],
    },
    "Morris & Dickson Co., LLC": {
        "pack_sizes": ["each", "case"],
        "pricing_note": "Independent-pharmacy generic programs",
        "price_examples": [
            {"item": "Rx distribution", "price": "Account terms", "unit": "per account"},
        ],
    },
    "Smith Drug Company": {
        "pack_sizes": ["each", "case"],
        "pricing_note": "Regional account terms",
        "price_examples": [
            {"item": "Rx distribution", "price": "Account terms", "unit": "per account"},
        ],
    },

    # ---------------- B2B marketplaces ----------------
    "Alibaba.com": {
        "pack_sizes": ["seller-defined: 1 kg bags → FCL containers"],
        "pricing_note": "Tiered per-MOQ pricing listed live; Trade Assurance escrow",
        "price_examples": [
            {"item": "Bulk supplement powders", "price": "$2–60", "unit": "kg (MOQ-dependent)"},
            {"item": "Finished softgels/capsules OEM", "price": "$0.01–0.05", "unit": "capsule"},
        ],
    },
    "Made-in-China.com": {
        "pack_sizes": ["seller-defined: kg drums → containers"],
        "pricing_note": "Onsite-check verified suppliers; negotiated pricing",
        "price_examples": [
            {"item": "Botanical extracts", "price": "$5–70", "unit": "kg (MOQ-dependent)"},
        ],
    },
    "IndiaMART": {
        "pack_sizes": ["seller-defined: kg → tons"],
        "pricing_note": "Quote-based; huge Indian pharma/excipient base",
        "price_examples": [
            {"item": "APIs & excipients", "price": "Quote", "unit": "kg lots"},
        ],
    },
    "Global Sources": {
        "pack_sizes": ["seller-defined"],
        "pricing_note": "Verified-manufacturer program; RFQ workflow",
        "price_examples": [
            {"item": "Health products & ingredients", "price": "Quote", "unit": "varies"},
        ],
    },
    "DHgate": {
        "pack_sizes": ["small-lot wholesale (1–100 units)"],
        "pricing_note": "Escrow protected small-batch pricing",
        "price_examples": [
            {"item": "Small-lot supplements", "price": "$1–15", "unit": "unit"},
        ],
    },
    "ThomasNet": {
        "pack_sizes": ["n/a (directory)"],
        "pricing_note": "US manufacturer directory with direct RFQ",
        "price_examples": [
            {"item": "Co-man/co-pack quotes", "price": "Quote", "unit": "per project"},
        ],
    },
    "EC21": {
        "pack_sizes": ["seller-defined"],
        "pricing_note": "Korea-based global B2B offers board",
        "price_examples": [
            {"item": "Chemical & pharma offers", "price": "Quote", "unit": "varies"},
        ],
    },
    "Pharmaoffer": {
        "pack_sizes": ["pilot kg → commercial tons"],
        "pricing_note": "Multi-supplier RFQ comparison, free for buyers",
        "price_examples": [
            {"item": "API quotes", "price": "Quote", "unit": "kg lots"},
        ],
    },
    "Knowde": {
        "pack_sizes": ["sample → drum → tote"],
        "pricing_note": "List pricing or quote carts set by producers",
        "price_examples": [
            {"item": "Nutraceutical actives", "price": "$10–200", "unit": "kg (typical range)"},
        ],
    },
    "CPHI Online": {
        "pack_sizes": ["n/a (RFQ platform)"],
        "pricing_note": "Buyer membership free tiers; quotes from verified GMP sites",
        "price_examples": [
            {"item": "API/excipient RFQs", "price": "Quote", "unit": "per RFQ"},
        ],
    },
    "EudraGMDP Database (EMA)": {
        "pack_sizes": ["n/a — register"],
        "pricing_note": "Free public access",
        "price_examples": [],
    },
    "NABP Accredited Distributor Search (VAWD)": {
        "pack_sizes": ["n/a — directory"],
        "pricing_note": "Free public lookup",
        "price_examples": [],
    },
    "FDA Establishment Registration & Listing": {
        "pack_sizes": ["n/a — register"],
        "pricing_note": "Free public access",
        "price_examples": [],
    },
}

MARKETPLACES = [
    {
        "name": "Alibaba.com",
        "category": "marketplace",
        "website": "https://www.alibaba.com",
        "country": "China",
        "location": "Hangzhou, CN (global reach)",
        "moq": "Set by seller; commonly 1–500 kg or 100+ units",
        "certifications": ["Trade Assurance escrow", "Supplier verification tiers"],
        "products": ["supplement raw materials", "APIs", "herbal extracts", "OEM finished supplements", "packaging"],
        "description": "World's largest B2B marketplace; filter by Verified Supplier, trade assurance and MOQ.",
        "tags": ["b2b", "oem", "global sourcing", "escrow"],
    },
    {
        "name": "Made-in-China.com",
        "category": "marketplace",
        "website": "https://www.made-in-china.com",
        "country": "China",
        "location": "Nanjing, CN (global reach)",
        "moq": "Seller-defined; typically 25–100 kg",
        "certifications": ["Onsite Check factory audits", "Verified Supplier badges"],
        "products": ["botanical extracts", "nutraceutical raws", "pharma machinery", "supplements"],
        "description": "Major Chinese B2B portal with audited-factory listings across nutraceutical supply.",
        "tags": ["b2b", "factory audits", "global sourcing"],
    },
    {
        "name": "IndiaMART",
        "category": "marketplace",
        "website": "https://www.indiamart.com",
        "country": "India",
        "location": "Noida, IN",
        "moq": "Seller-defined; quote-based",
        "certifications": ["Supplier verification levels", "GST-registered sellers"],
        "products": ["APIs", "excipients", "ayurvedic/herbal ingredients", "pharma machinery"],
        "description": "India's largest B2B marketplace with deep pharmaceutical and herbal supplier base.",
        "tags": ["b2b", "india", "quote-based"],
    },
    {
        "name": "Global Sources",
        "category": "marketplace",
        "website": "https://www.globalsources.com",
        "country": "Hong Kong/China",
        "location": "Hong Kong SAR",
        "moq": "Seller-defined",
        "certifications": ["Verified Manufacturer program"],
        "products": ["health supplements", "ingredients", "consumer health devices"],
        "description": "Asia-sourcing B2B platform known for verified-manufacturer vetting and trade shows.",
        "tags": ["b2b", "verified suppliers", "trade shows"],
    },
    {
        "name": "DHgate",
        "category": "marketplace",
        "website": "https://www.dhgate.com",
        "country": "China",
        "location": "Beijing, CN (global reach)",
        "moq": "Very low; single-carton lots common",
        "certifications": ["Buyer-protection escrow"],
        "products": ["small-lot supplements", "vitamins", "sports nutrition"],
        "description": "Small-batch wholesale arm of the Chinese export ecosystem; low MOQs with escrow.",
        "tags": ["b2b", "small lots", "escrow"],
    },
    {
        "name": "ThomasNet",
        "category": "marketplace",
        "website": "https://www.thomasnet.com",
        "country": "USA",
        "location": "New York, NY",
        "moq": "n/a — RFQ directory",
        "certifications": ["North American manufacturer focus"],
        "products": ["co-manufacturers", "co-packers", "ingredient distributors", "private label"],
        "description": "Directory of North American industrial and nutraceutical manufacturers with direct RFQ.",
        "tags": ["b2b", "directory", "rfq", "usa"],
    },
    {
        "name": "EC21",
        "category": "marketplace",
        "website": "https://www.ec21.com",
        "country": "South Korea",
        "location": "Seoul, KR",
        "moq": "Offer-based",
        "certifications": ["Gold/Silver supplier membership tiers"],
        "products": ["chemicals", "pharmaceuticals", "food additives", "herbal materials"],
        "description": "Korean global B2B platform strong in chemicals and pharma trade offers.",
        "tags": ["b2b", "chemicals", "trade offers"],
    },
]


def enrich(rows) -> list[dict]:
    """Attach pack sizes / indicative pricing to each supplier entry."""
    # Full-line distributors carry the common generics; make them findable by molecule name
    for r in rows:
        if r["name"] in FULL_LINE_DISTRIBUTORS:
            prods = r.setdefault("products", [])
            for g in COMMON_GENERICS:
                if g not in prods:
                    prods.append(g)
    for r in rows:
        extra = PRICE_AND_PACKS.get(r["name"], {})
        r.setdefault("pack_sizes", extra.get("pack_sizes", []))
        r.setdefault("price_examples", extra.get("price_examples", []))
        r.setdefault("pricing_note", extra.get("pricing_note", ""))
    return rows


# ---------------------------------------------------------------------------
# Sourcing platforms & regulatory directories (licensed/verified channels)
# ---------------------------------------------------------------------------
SOURCING_PLATFORMS = [
    {
        "name": "Pharmaoffer",
        "category": "marketplace",
        "website": "https://www.pharmaoffer.com",
        "country": "Netherlands",
        "location": "Leiden, NL",
        "moq": "Quote-based; pilot to commercial",
        "certifications": ["Verified CDMO/API profiles", "DMF/CEP status shown"],
        "products": ["APIs", "excipients", "CDMO services", "finished dose manufacturing"],
        "description": "B2B platform to find and quote vetted API manufacturers and contract manufacturers worldwide.",
        "tags": ["b2b", "api sourcing", "cdmo", "rfq"],
    },
    {
        "name": "Knowde",
        "category": "marketplace",
        "website": "https://www.knowde.com",
        "country": "USA",
        "location": "San Jose, CA",
        "moq": "Supplier-defined; sample requests supported",
        "certifications": ["Direct-from-producer listings", "TDS/SDS docs attached"],
        "products": ["nutraceutical ingredients", "functional actives", "chemicals", "flavors"],
        "description": "Online marketplace where ingredient producers list products with technical documentation and quotes.",
        "tags": ["b2b", "ingredients", "documentation"],
    },
    {
        "name": "CPHI Online",
        "category": "marketplace",
        "website": "https://www.cphi.com",
        "country": "Netherlands",
        "location": "Amsterdam, NL (global network)",
        "moq": "n/a — RFQ platform",
        "certifications": ["Verified supplier profiles", "GMP site info listed"],
        "products": ["APIs", "excipients", "contract manufacturing", "packaging", "machinery"],
        "description": "Informa's pharma supply-chain platform connecting buyers with GMP suppliers year-round plus CPHI trade shows.",
        "tags": ["b2b", "directory", "rfq", "trade shows"],
    },
    {
        "name": "EudraGMDP Database (EMA)",
        "category": "pharma_dist",
        "website": "https://eudragmdp.ema.europa.eu",
        "country": "EU/EEA",
        "location": "Amsterdam, NL (EMA)",
        "moq": "n/a — official register",
        "certifications": ["Official EU database", "GDP certificate status"],
        "products": ["wholesale distribution authorizations", "GMP certificates", "manufacturing authorizations"],
        "description": "EU regulator-run register of licensed wholesale distributors and GDP/GMP certificate status across member states.",
        "tags": ["regulatory", "verify wholesalers", "gdp"],
    },
    {
        "name": "NABP Accredited Distributor Search (VAWD)",
        "category": "pharma_dist",
        "website": "https://nabp.pharmacy",
        "country": "USA",
        "location": "Mount Prospect, IL",
        "moq": "n/a — accreditation directory",
        "certifications": ["VAWD accreditation", "State licensure verified by NABP"],
        "products": ["accredited wholesale distributor lookup", "pharmacy verification"],
        "description": "Search tool from the National Association of Boards of Pharmacy for VAWD-accredited drug wholesalers.",
        "tags": ["regulatory", "verify distributors", "accreditation"],
    },
    {
        "name": "FDA Establishment Registration & Listing",
        "category": "api",
        "website": "https://www.accessdata.fda.gov/scripts/cder/drls/",
        "country": "USA",
        "location": "Silver Spring, MD",
        "moq": "n/a — official register",
        "certifications": ["Official FDA database"],
        "products": ["registered drug manufacturers", "repackers", "contract manufacturers", "API facilities"],
        "description": "Verify that a drug facility is FDA-registered and what operations it is authorized to perform.",
        "tags": ["regulatory", "due diligence", "facility verification"],
    },
]

# ---------------------------------------------------------------------------
# Drug / molecule catalog — lets users search by actual drug names.
# Sourcing notes describe legitimate channels only (DMF-holding API plants,
# licensed generic manufacturers, licensed wholesale distribution).
# Rx entries require a valid prescription; nothing here is medical advice.
# ---------------------------------------------------------------------------
DRUGS = [
    {"name": "Sertraline", "kind": "rx", "description": "SSRI antidepressant (Zoloft); widely prescribed generic.",
     "sourcing": "API from DMF/CEP-holding plants (IN/CN/EU); finished generics via licensed manufacturers and full-line distributors with valid prescription."},
    {"name": "Metformin", "kind": "rx", "description": "Biguanide oral antidiabetic, first-line type 2 diabetes therapy.",
     "sourcing": "High-volume API and finished generics from Indian manufacturers; US distribution via big-three wholesalers."},
    {"name": "Atorvastatin", "kind": "rx", "description": "Statin for hyperlipidemia; among the most-dispensed generics worldwide.",
     "sourcing": "APIs from DMF holders; finished tablets via licensed generic manufacturers."},
    {"name": "Amlodipine", "kind": "rx", "description": "Calcium-channel blocker for hypertension/angina.",
     "sourcing": "Generic API and finished dose widely available through licensed channels."},
    {"name": "Lisinopril", "kind": "rx", "description": "ACE inhibitor antihypertensive.",
     "sourcing": "Commodity API; finished generics via licensed wholesalers."},
    {"name": "Omeprazole", "kind": "rx", "description": "Proton-pump inhibitor for GERD/ulcers (also OTC in many markets).",
     "sourcing": "API plus OTC finished product from GMP plants; enteric formulations common."},
    {"name": "Amoxicillin", "kind": "rx", "description": "Broad-spectrum penicillin-class antibiotic.",
     "sourcing": "Fermentation-derived API (CN/IN/EU); capsules/tablets/suspensions via licensed makers."},
    {"name": "Azithromycin", "kind": "rx", "description": "Macrolide antibiotic (Zithromax).",
     "sourcing": "API from DMF holders; finished generics widely distributed."},
    {"name": "Doxycycline", "kind": "rx", "description": "Tetracycline antibiotic; also antimalarial prophylaxis.",
     "sourcing": "Commodity API; finished generics via licensed channels."},
    {"name": "Gabapentin", "kind": "rx", "description": "Neuropathic pain / seizure adjunct.",
     "sourcing": "US-controlled-adjacent handling; API and generics via licensed manufacturers."},
    {"name": "Prednisone", "kind": "rx", "description": "Corticosteroid anti-inflammatory.",
     "sourcing": "API from steroid-specialty plants (CN/IN); finished generics common."},
    {"name": "Losartan", "kind": "rx", "description": "ARB antihypertensive.",
     "sourcing": "API supply subject to nitrosamine controls; DMF holders listed on sourcing platforms."},
    {"name": "Montelukast", "kind": "rx", "description": "Leukotriene antagonist for asthma/allergies.",
     "sourcing": "Finished generics via licensed manufacturers."},
    {"name": "Duloxetine", "kind": "rx", "description": "SNRI for depression/anxiety/neuropathic pain.",
     "sourcing": "API from IN/CN plants; high-volume generic finished dose."},
    {"name": "Escitalopram", "kind": "rx", "description": "SSRI antidepressant (Lexapro).",
     "sourcing": "API via DMF holders; generics via licensed makers."},
    {"name": "Bupropion", "kind": "rx", "description": "NDRI antidepressant / smoking cessation (Wellbutrin, Zyban).",
     "sourcing": "Finished generics via licensed manufacturers and distributors."},
    {"name": "Alprazolam", "kind": "rx", "description": "Benzodiazepine anxiolytic — Schedule IV controlled substance.",
     "sourcing": "DEA-registered manufacturers/distributors ONLY; strict quotas. Never source outside licensed channels."},
    {"name": "Ibuprofen", "kind": "otc", "description": "NSAID pain reliever/anti-inflammatory.",
     "sourcing": "Commodity API ($8–15/kg) from CN/IN plants; OTC finished goods from contract manufacturers."},
    {"name": "Acetaminophen / Paracetamol", "kind": "otc", "description": "Analgesic/antipyretic (Tylenol).",
     "sourcing": "One of the highest-volume APIs globally; Mallinckrodt and Chinese plants dominate; OTC private label widespread."},
    {"name": "Aspirin", "kind": "otc", "description": "NSAID analgesic and antiplatelet.",
     "sourcing": "Mature commodity API; OTC formats from many GMP sites."},
    {"name": "Loratadine", "kind": "otc", "description": "Non-drowsy antihistamine (Claritin).",
     "sourcing": "OTC API + finished generics; private label common."},
    {"name": "Cetirizine", "kind": "otc", "description": "Antihistamine (Zyrtec).",
     "sourcing": "OTC API from CN/IN; store-brand finished packs."},
    {"name": "Naproxen", "kind": "otc", "description": "NSAID (Aleve).",
     "sourcing": "API and OTC finished goods via licensed channels."},
    {"name": "Melatonin", "kind": "supplement", "description": "Sleep-cycle supplement hormone.",
     "sourcing": "Synthetic or fermentation API-grade powder ($30–80/kg); gummies/capsules via co-packers."},
    {"name": "Creatine monohydrate", "kind": "supplement", "description": "Sports-performance ergogenic aid.",
     "sourcing": "Chinese Creapure-style reactors dominate; $12–30/kg depending on grade."},
    {"name": "Whey protein isolate", "kind": "supplement", "description": "Milk-derived sports protein (~90% protein).",
     "sourcing": "US/EU/NZ dairies; $10–18/kg bulk; instantized grades available."},
    {"name": "Caffeine anhydrous", "kind": "supplement", "description": "Synthetic stimulant powder for energy products.",
     "sourcing": "CN/IN/German synthesis; $10–20/kg; FDA GRAS provisioned."},
    {"name": "Ashwagandha extract (withanolides)", "kind": "supplement", "description": "Adaptogenic botanical extract (KSM-66, Sensoril branded).",
     "sourcing": "Indian root extractors; 2.5–5% withanolide standardizations $25–60/kg."},
    {"name": "Curcumin 95%", "kind": "supplement", "description": "Turmeric-derived anti-inflammatory extract.",
     "sourcing": "Indian extraction hubs; $25–55/kg; bioavailability-enhanced forms command premiums."},
    {"name": "Omega-3 EPA/DHA concentrates", "kind": "supplement", "description": "Fish/algae oil fatty acids.",
     "sourcing": "Peru/Chile/NO processors; rTG concentrates $40–120/kg."},
    {"name": "Magnesium glycinate", "kind": "supplement", "description": "Chelated mineral for sleep/muscle support.",
     "sourcing": "Chinese chelation plants; $14–24/kg bulk."},
    {"name": "Vitamin C (ascorbic acid)", "kind": "supplement", "description": "Essential vitamin antioxidant.",
     "sourcing": "China (DSM/Weishang cluster) dominates; $8–15/kg commodity."},
    {"name": "Vitamin D3 (cholecalciferol) 100,000 IU/g", "kind": "supplement", "description": "Fat-soluble vitamin concentrate powder.",
     "sourcing": "Swiss/Chinese producers; priced per MIU activity units."},
    {"name": "CoQ10 (ubiquinone/ubiquinol)", "kind": "supplement", "description": "Mitochondrial cofactor supplement.",
     "sourcing": "Japanese microbial fermentation leads; ubiquinol premium vs ubiquinone ($200–600/kg)."},
    {"name": "NAC (N-acetyl cysteine)", "kind": "supplement", "description": "Mucolytic amino-acid derivative.",
     "sourcing": "Japanese/Chinese synthesis; regulatory status varies by market."},
    {"name": "Berberine HCl", "kind": "supplement", "description": "Botanical alkaloid for metabolic support.",
     "sourcing": "Chinese extraction (barberry/Phellodendron); $20–50/kg."},
    {"name": "Collagen peptides (Type I/III)", "kind": "supplement", "description": "Hydrolyzed bovine/marine protein.",
     "sourcing": "German/Brazilian/Japanese gelatin houses; $12–30/kg; marine versions higher."},
    {"name": "Probiotics (Lactobacillus/Bifidobacterium blends)", "kind": "supplement", "description": "Live-culture CFU-counted blends.",
     "sourcing": "Danish/US/Japanese culture houses; quoted per CFU formulation."},
]

# ---------------------------------------------------------------------------
# Global expansion: China, Korea, India, US, Canada, UK, Germany
# ---------------------------------------------------------------------------
GLOBAL_SUPPLIERS = [
    # ---- India ----
    {
        "name": "Divi's Laboratories",
        "category": "api",
        "website": "https://www.divislaboratories.com",
        "country": "India",
        "location": "Hyderabad, IN",
        "moq": "Commercial tons; custom campaigns",
        "certifications": ["US FDA-inspected", "EU GMP", "EDQM CEPs", "JSFA/Kosher/Halal"],
        "products": ["generic APIs", "nutraceutical actives", "carotenoids", "custom synthesis"],
        "description": "One of the world's largest API and nutraceutical-ingredient manufacturers with patents-differentiated custom work.",
        "tags": ["big pharma india", "custom synthesis"],
        "pack_sizes": ["25 kg fiber drum", "pallet", "container"],
        "pricing_note": "Contract pricing at scale; among lowest-cost global producers",
        "price_examples": [{"item": "Generic APIs", "price": "Quote / contract", "unit": "kg"}],
    },
    {
        "name": "Dr. Reddy's Laboratories",
        "category": "api",
        "website": "https://www.drreddys.com",
        "country": "India",
        "location": "Hyderabad, IN",
        "moq": "Commercial volumes",
        "certifications": ["US FDA", "UK MHRA", "EMA inspections", "DMFs/CEPs"],
        "products": ["finished generics", "APIs", "biosimilars", "OTC"],
        "description": "Global generics major supplying finished doses to regulated markets plus API business unit.",
        "tags": ["generics major", "regulated markets"],
        "pack_sizes": ["commercial packs", "bulk containers"],
        "pricing_note": "Tender/contract pricing",
        "price_examples": [{"item": "Finished generics", "price": "Contract", "unit": "per tender"}],
    },
    {
        "name": "Laurus Labs",
        "category": "api",
        "website": "https://www.lauruslabs.com",
        "country": "India",
        "location": "Visakhapatnam, IN",
        "moq": "Commercial scale",
        "certifications": ["US FDA", "EU GMP", "WHO PQ", "Korea MFDS"],
        "products": ["ARV APIs", "oncology APIs", "hepatitis APIs", "CDMO services"],
        "description": "Fast-growing API house strong in antiretrovirals and onco molecules; expanding into finished doses.",
        "tags": ["api specialist", "cdmo"],
        "pack_sizes": ["25 kg drums", "bulk"],
        "pricing_note": "Volume contracts",
        "price_examples": [{"item": "Specialty APIs", "price": "Quote", "unit": "kg"}],
    },
    {
        "name": "Cipla",
        "category": "pharma_dist",
        "website": "https://www.cipla.com",
        "country": "India",
        "location": "Mumbai, IN",
        "moq": "Commercial/tender",
        "certifications": ["US FDA plants", "WHO GMP", "PIC/S markets"],
        "products": ["respiratory medicines", "generics", "OTC", "export supply"],
        "description": "Indian generics powerhouse famous for respiratory inhalers and affordable medicines across 80+ countries.",
        "tags": ["respiratory", "emerging markets"],
        "pack_sizes": ["retail packs", "hospital bulk"],
        "pricing_note": "Tiered export pricing",
        "price_examples": [{"item": "Export generics", "price": "Quote", "unit": "per order"}],
    },
    # ---- China ----
    {
        "name": "Zhejiang Hisun Pharmaceutical",
        "category": "api",
        "website": "https://www.hisunpharm.com",
        "country": "China",
        "location": "Taizhou, Zhejiang, CN",
        "moq": "Kg pilot → commercial tons",
        "certifications": ["US FDA-inspected sites", "EU CEPs", "Japan PMDA", "WHO PQ"],
        "products": ["antibiotic APIs", "specialty generics APIs", "CDMO"],
        "description": "Major exporter of antibiotic and specialty APIs with multiple FDA-audited workshops.",
        "tags": ["api exporter", "antibiotics"],
        "pack_sizes": ["25 kg drum", "pallet"],
        "pricing_note": "FOB quotes; aggressive at volume",
        "price_examples": [{"item": "Antibiotic APIs", "price": "$40–300", "unit": "kg FOB"}],
    },
    {
        "name": "CSPC Pharmaceutical Group",
        "category": "api",
        "website": "https://www.cspc.com.cn",
        "country": "China",
        "location": "Shijiazhuang, Hebei, CN",
        "moq": "Commercial scale",
        "certifications": ["US FDA", "EU GMP", "CEPs"],
        "products": ["antibiotics (7-ACA chain)", "vitamin C", "bulk APIs", "finished drugs"],
        "description": "Among China's biggest pharma groups; fermentation giant for antibiotics and vitamin C.",
        "tags": ["fermentation", "vertical integration"],
        "pack_sizes": ["drums", "containers"],
        "pricing_note": "Commodity-scale pricing",
        "price_examples": [{"item": "Vitamin C API", "price": "$6–11", "unit": "kg FOB"}],
    },
    {
        "name": "Zhejiang Huahai Pharmaceutical",
        "category": "api",
        "website": "https://www.huahai.cn",
        "country": "China",
        "location": "Taizhou, Zhejiang, CN",
        "moq": "Commercial volumes",
        "certifications": ["US FDA (first Chinese firm approved for US finished dose)", "EU GMP"],
        "products": ["cardiovascular APIs", "central-nervous APIs", "finished generics"],
        "description": "API-and-finished-dose exporter known for losartan-family and CNS molecules in regulated markets.",
        "tags": ["regulatory track record"],
        "pack_sizes": ["25 kg drum", "commercial packs"],
        "pricing_note": "Contract quotes",
        "price_examples": [{"item": "CV/CNS APIs", "price": "Quote", "unit": "kg"}],
    },
    # ---- Korea ----
    {
        "name": "Celltrion",
        "category": "pharma_dist",
        "website": "https://www.celltrion.com",
        "country": "South Korea",
        "location": "Incheon, KR",
        "moq": "Commercial/biosimilar contracts",
        "certifications": ["US FDA", "EMA", "WHO PQ"],
        "products": ["biosimilars (Remsima etc.)", "mAbs", "COVID therapeutics"],
        "description": "World-leading biosimilar manufacturer with massive mammalian-cell capacity.",
        "tags": ["biologics", "biosimilars"],
        "pack_sizes": ["vial/pre-filled syringe commercial packs"],
        "pricing_note": "Hospital/tender contracts",
        "price_examples": [{"item": "Biosimilars", "price": "Contract", "unit": "per program"}],
    },
    {
        "name": "Yuhan Corporation",
        "category": "pharma_dist",
        "website": "https://www.yuhan.co.kr",
        "country": "South Korea",
        "location": "Seoul, KR",
        "moq": "Domestic/commercial",
        "certifications": ["Korea MFDS GMP", "exports to 40+ countries"],
        "products": ["Rx brands", "generics", "OTC", "APIs (via Yuhan Corp affiliates)"],
        "description": "One of Korea's oldest and largest pharmaceutical companies with broad Rx portfolio.",
        "tags": ["korean major"],
        "pack_sizes": ["commercial packs"],
        "pricing_note": "Distribution agreements",
        "price_examples": [{"item": "Portfolio supply", "price": "Contract", "unit": "per market"}],
    },
    {
        "name": "JW Pharmaceutical",
        "category": "pharma_dist",
        "website": "https://www.jw-pharma.co.kr",
        "country": "South Korea",
        "location": "Seoul, KR",
        "moq": "Wholesale accounts",
        "certifications": ["MFDS-licensed wholesaler & manufacturer"],
        "products": ["IV solutions", "injectables", "national distribution network"],
        "description": "Korea's largest IV-fluids maker operating a nationwide pharma wholesale network.",
        "tags": ["wholesale network", "injectables"],
        "pack_sizes": ["case/pallet hospital supply"],
        "pricing_note": "Hospital contract pricing",
        "price_examples": [{"item": "IV solutions", "price": "Contract", "unit": "case"}],
    },
    # ---- USA additions ----
    {
        "name": "Pfizer CentreOne",
        "category": "api",
        "website": "https://www.pfizercentreone.com",
        "country": "USA",
        "location": "New York, NY (global network)",
        "moq": "Development → commercial campaigns",
        "certifications": ["Pfizer GMP network", "global site licenses"],
        "products": ["sterile injectables CDMO", "APIs", "specialty dose forms", "contract manufacturing"],
        "description": "Pfizer's global CDMO arm offering sterile fill-finish, APIs and complex dose forms.",
        "tags": ["cdmo", "sterile", "big-pharma quality"],
        "pack_sizes": ["clinical lots → commercial batches"],
        "pricing_note": "Program-based contracting",
        "price_examples": [{"item": "CDMO programs", "price": "Quote", "unit": "per project"}],
    },
    {
        "name": "Amneal Pharmaceuticals",
        "category": "pharma_dist",
        "website": "https://www.amneal.com",
        "country": "USA",
        "location": "Bridgewater, NJ",
        "moq": "Wholesale accounts",
        "certifications": ["FDA-approved ANDAs", "DEA registrations where applicable"],
        "products": ["generics", "branded Rx", "injectables", "biosimilars pipeline"],
        "description": "Top-5 US generics maker supplying retail/pharmacy channels via standard wholesale networks.",
        "tags": ["us generics", "vertically integrated"],
        "pack_sizes": ["bottles", "cases"],
        "pricing_note": "WAC via distributors",
        "price_examples": [{"item": "Generics portfolio", "price": "WAC", "unit": "per account"}],
    },
    {
        "name": "Cambrex",
        "category": "api",
        "website": "https://cambrex.com",
        "country": "USA",
        "location": "East Rutherford, NJ (global sites)",
        "moq": "Gram R&D → multi-ton commercial",
        "certifications": ["FDA/EMA-inspected API sites", "controlled-substance licensed"],
        "products": ["small-molecule APIs", "controlled substances", "HPAPIs", "process R&D"],
        "description": "Pure-play small-molecule API CDMO with DEA-licensed controlled-substance capability.",
        "tags": ["api cdmo", "controlled substances licensed"],
        "pack_sizes": ["g → kg → ton"],
        "pricing_note": "Stage-gated development pricing",
        "price_examples": [{"item": "Custom APIs", "price": "Quote", "unit": "per campaign"}],
    },
    # ---- Canada ----
    {
        "name": "Apotex",
        "category": "pharma_dist",
        "website": "https://www.apotex.com",
        "country": "Canada",
        "location": "Toronto, ON",
        "moq": "Wholesale/tender",
        "certifications": ["Health Canada establishment licences", "FDA/EMA-export approvals"],
        "products": ["generic Rx", "OTC", "APIs (Apotex Pharmachem)", "international division"],
        "description": "Canada's largest generic-drug manufacturer exporting to 100+ countries.",
        "tags": ["canadian generics major"],
        "pack_sizes": ["bottles", "bulk export packs"],
        "pricing_note": "Tender and wholesale terms",
        "price_examples": [{"item": "Generics", "price": "Contract", "unit": "per account"}],
    },
    {
        "name": "Pharmascience Inc.",
        "category": "pharma_dist",
        "website": "https://www.pharmascience.com",
        "country": "Canada",
        "location": "Montreal, QC",
        "moq": "Wholesale accounts",
        "certifications": ["Health Canada licensed", "FDA-export compliant plants"],
        "products": ["generic Rx", "OTC liquids", "narcotics-licensed production"],
        "description": "Major Canadian generic manufacturer with one of the country's largest Rx portfolios.",
        "tags": ["canadian generics", "liquids specialist"],
        "pack_sizes": ["bottles/cases"],
        "pricing_note": "Provincial formulary pricing",
        "price_examples": [{"item": "Generics", "price": "Formulary/contract", "unit": "per account"}],
    },
    {
        "name": "Jamieson Wellness",
        "category": "finished",
        "website": "https://www.jamiesonwellness.com",
        "country": "Canada",
        "location": "Toronto, ON",
        "moq": "Case quantities; private label runs",
        "certifications": ["GMP", "Health Canada site licence", "export to 45+ countries"],
        "products": ["vitamins", "minerals", "probiotics", "private label manufacturing"],
        "description": "Canada's leading vitamin brand owner with large GMP contract-manufacturing capacity.",
        "tags": ["brand owner", "private label canada"],
        "pack_sizes": ["retail bottles", "master cases"],
        "pricing_note": "Wholesale ~40% off MSRP; private label quoted",
        "price_examples": [{"item": "Finished vitamins", "price": "$3–18", "unit": "bottle wholesale"}],
    },
    # ---- UK ----
    {
        "name": "Alliance Healthcare UK",
        "category": "pharma_dist",
        "website": "https://www.alliance-healthcare.co.uk",
        "country": "United Kingdom",
        "location": "London, UK (Cencora group)",
        "moq": "Account-based daily orders",
        "certifications": ["MHRA WDA(L) wholesale licence"],
        "products": ["full-line NHS & pharmacy distribution", "short-line specials", "pre-wholesale"],
        "description": "One of two full-line UK pharma wholesalers serving community pharmacy and hospitals.",
        "tags": ["uk distribution", "mhra licensed"],
        "pack_sizes": ["each/case"],
        "pricing_note": "NHS drug tariff + account discounts",
        "price_examples": [{"item": "Full-line distribution", "price": "Account terms", "unit": "per account"}],
    },
    {
        "name": "Mawdsleys Brooks",
        "category": "pharma_dist",
        "website": "https://www.mawdsleys.co.uk",
        "country": "United Kingdom",
        "location": "Bristol, UK",
        "moq": "Independent-pharmacy friendly",
        "certifications": ["MHRA WDA(L)", "RPS-recognised wholesaler"],
        "products": ["full-line wholesale", "parallel imports", "vaccine cold-chain"],
        "description": "Family-run UK short/full-line wholesaler popular with independents since 1845.",
        "tags": ["uk independent pharmacies"],
        "pack_sizes": ["each/case"],
        "pricing_note": "Competitive generic pricing lines",
        "price_examples": [{"item": "Generics", "price": "Account terms", "unit": "per account"}],
    },
    {
        "name": "Thornton & Ross (STADA)",
        "category": "finished",
        "website": "https://www.thorntonross.com",
        "country": "United Kingdom",
        "location": "Huddersfield, UK",
        "moq": "Trade packs via wholesalers",
        "certifications": ["MHRA MIA manufacturing", "EU GMP (STADA network)"],
        "products": ["OTC brands (Covonia, Zovirax UK)", "own-brand labels", "licensing deals"],
        "description": "Britain's largest independent OTC manufacturer, part of STADA group.",
        "tags": ["otc manufacturer uk"],
        "pack_sizes": ["trade packs", "pallets"],
        "pricing_note": "Brand/licensing route to market",
        "price_examples": [{"item": "OTC ranges", "price": "Trade price", "unit": "per line"}],
    },
    # ---- Germany ----
    {
        "name": "PHOENIX group",
        "category": "pharma_dist",
        "website": "https://www.phoenixgroup.com",
        "country": "Germany",
        "location": "Mannheim, DE (29 EU countries)",
        "moq": "Account-based",
        "certifications": ["EU wholesale authorizations per member state", "GDP certified"],
        "products": ["full-line European distribution", "pre-wholesale", "hospital supply"],
        "description": "Europe's largest pharmaceutical wholesale group — the continent's medicine supply backbone.",
        "tags": ["europe biggest wholesaler"],
        "pack_sizes": ["each/case/pallet"],
        "pricing_note": "Lauer-tariff based German pricing; national contracts",
        "price_examples": [{"item": "Full-line supply", "price": "Tariff/account", "unit": "per market"}],
    },
    {
        "name": "NOWEDA eG",
        "category": "pharma_dist",
        "website": "https://www.noweda.de",
        "country": "Germany",
        "location": "Essen, DE",
        "moq": "Member pharmacy accounts",
        "certifications": ["German wholesale authorization", "GDP"],
        "products": ["full-line Rx distribution", "OTC", "pharmacy cooperation programs"],
        "description": "Pharmacist-owned cooperative wholesaler delivering to thousands of German Apotheken.",
        "tags": ["cooperative", "german market"],
        "pack_sizes": ["each/case"],
        "pricing_note": "Member conditions",
        "price_examples": [{"item": "Apothek supply", "price": "Member terms", "unit": "per account"}],
    },
    {
        "name": "Evonik (Health Care)",
        "category": "ingredient",
        "website": "https://health.evonik.com",
        "country": "Germany",
        "location": "Essen, DE (global sites)",
        "moq": "Sample → commercial tons",
        "certifications": ["GMP excipient sites", "Ph.Eur./USP-NF compendial grades"],
        "products": ["EUDRAGIT polymers", "excipients", "lipid systems (SMEDDS)", "collagen medical devices"],
        "description": "Premier functional-excipient maker — EUDRAGIT enteric coatings are the industry standard.",
        "tags": ["excipients leader", "drug delivery"],
        "pack_sizes": ["1 kg sample", "25 kg", "pallet"],
        "pricing_note": "Premium functional polymers",
        "price_examples": [{"item": "EUDRAGIT polymers", "price": "$40–120", "unit": "kg"}],
    },
]


FULL_LINE_DISTRIBUTORS = {
    "McKesson Corporation",
    "Cencora (formerly AmerisourceBergen)",
    "Cardinal Health (Pharmaceutical Segment)",
    "Morris & Dickson Co., LLC",
    "Smith Drug Company",
    "Alliance Healthcare UK",
    "PHOENIX group",
    "NOWEDA eG",
}
COMMON_GENERICS = [
    "sertraline", "metformin", "atorvastatin", "amlodipine", "lisinopril",
    "omeprazole", "amoxicillin", "ibuprofen", "acetaminophen",
]

ALL_SUPPLIERS: list[dict] = validate(enrich(SUPPLIERS + MARKETPLACES + SOURCING_PLATFORMS + GLOBAL_SUPPLIERS))


if __name__ == "__main__":
    print(f"{len(ALL_SUPPLIERS)} suppliers validated")
